<template>
  <ul>
    <li>AJAR</li>
    <li>AJEE</li>
    <li>AJIVA</li>
    <li>AJUGA</li>
    <li>BANJO</li>
    <li>BIJOU</li>
    <li>CAJON</li>
    <li>DJIN(S)</li>
    <li>DJINN</li>
    <li>DOJO(S)</li>
    <li>EJECT</li>
    <li>ENJOY</li>
    <li>FJELD</li>
    <li>FJORD</li>
    <li>FUJI(S)</li>
    <li>GANJA</li>
    <li>HADJ</li>
    <li>HADJI</li>
    <li>HAJ</li>
    <li>HAJES</li>
    <li>HAJI(S)</li>
    <li>HAJJ</li>
    <li>HAJJI</li>
    <li>HIJAB</li>
    <li>JAB(S)</li>
    <li>JABOT</li>
    <li>JACAL</li>
    <li>JACK(S)</li>
    <li>JACKY</li>
    <li>JADE(S)</li>
    <li>JADED</li>
    <li>JAG(S)</li>
    <li>JAGER</li>
    <li>JAGG(S)</li>
    <li>JAGGY</li>
    <li>JAGRA</li>
    <li>JAIL(S)</li>
    <li>JAKE(S)</li>
    <li>JALAP</li>
    <li>JALOP</li>
    <li>JAM(S)</li>
    <li>JAMB(S)</li>
    <li>JAMBE</li>
    <li>JAMMY</li>
    <li>JANE(S)</li>
    <li>JANKY</li>
    <li>JANTY</li>
    <li>JAPAN</li>
    <li>JAPE(S)</li>
    <li>JAPED</li>
    <li>JAPER</li>
    <li>JAR(S)</li>
    <li>JARL(S)</li>
    <li>JATO(S)</li>
    <li>JAUK(S)</li>
    <li>JAUNT</li>
    <li>JAUP(S)</li>
    <li>JAVA(S)</li>
    <li>JAW(S)</li>
    <li>JAWAN</li>
    <li>JAWED</li>
    <li>JAY(S)</li>
    <li>JAZZ</li>
    <li>JAZZY</li>
    <li>JEAN(S)</li>
    <li>JEBEL</li>
    <li>JEE(S)</li>
    <li>JEED</li>
    <li>JEEP(S)</li>
    <li>JEER(S)</li>
    <li>JEEZ</li>
    <li>JEFE(S)</li>
    <li>JEHAD</li>
    <li>JEHU(S)</li>
    <li>JELL(S)</li>
    <li>JELLY</li>
    <li>JEMMY</li>
    <li>JENNY</li>
    <li>JEON</li>
    <li>JERID</li>
    <li>JERK(S)</li>
    <li>JERKY</li>
    <li>JERRY</li>
    <li>JESS</li>
    <li>JESSE</li>
    <li>JEST(S)</li>
    <li>JET(S)</li>
    <li>JETE(S)</li>
    <li>JETON</li>
    <li>JETTY</li>
    <li>JEU</li>
    <li>JEUX</li>
    <li>JEWED</li>
    <li>JEWEL</li>
    <li>JIAO</li>
    <li>JIB(S)</li>
    <li>JIBB(S)</li>
    <li>JIBE(S)</li>
    <li>JIBED</li>
    <li>JIBER</li>
    <li>JIFF(S)</li>
    <li>JIFFY</li>
    <li>JIG(S)</li>
    <li>JIGGY</li>
    <li>JIHAD</li>
    <li>JILL(S)</li>
    <li>JILT(S)</li>
    <li>JIMMY</li>
    <li>JIMP</li>
    <li>JIMPY</li>
    <li>JIN(S)</li>
    <li>JINGO</li>
    <li>JINK(S)</li>
    <li>JINN(S)</li>
    <li>JINNI</li>
    <li>JINX</li>
    <li>JISM(S)</li>
    <li>JIVE(S)</li>
    <li>JIVED</li>
    <li>JIVER</li>
    <li>JIVEY</li>
    <li>JIVY</li>
    <li>JNANA</li>
    <li>JO</li>
    <li>JOB(S)</li>
    <li>JOCK(S)</li>
    <li>JOCKO</li>
    <li>JOE(S)</li>
    <li>JOEY(S)</li>
    <li>JOG(S)</li>
    <li>JOHN(S)</li>
    <li>JOIN(S)</li>
    <li>JOINT</li>
    <li>JOIST</li>
    <li>JOKE(S)</li>
    <li>JOKED</li>
    <li>JOKER</li>
    <li>JOKEY</li>
    <li>JOKY</li>
    <li>JOLE(S)</li>
    <li>JOLLY</li>
    <li>JOLT(S)</li>
    <li>JOLTY</li>
    <li>JOMON</li>
    <li>JONES</li>
    <li>JORAM</li>
    <li>JORUM</li>
    <li>JOSH</li>
    <li>JOSS</li>
    <li>JOT(S)</li>
    <li>JOTA(S)</li>
    <li>JOTTY</li>
    <li>JOUAL</li>
    <li>JOUK(S)</li>
    <li>JOULE</li>
    <li>JOUST</li>
    <li>JOW(S)</li>
    <li>JOWAR</li>
    <li>JOWED</li>
    <li>JOWL(S)</li>
    <li>JOWLY</li>
    <li>JOY(S)</li>
    <li>JOYED</li>
    <li>JUBA(S)</li>
    <li>JUBE(S)</li>
    <li>JUCO(S)</li>
    <li>JUDAS</li>
    <li>JUDGE</li>
    <li>JUDO(S)</li>
    <li>JUG(S)</li>
    <li>JUGA</li>
    <li>JUGAL</li>
    <li>JUGUM</li>
    <li>JUICE</li>
    <li>JUICY</li>
    <li>JUJU(S)</li>
    <li>JUKE(S)</li>
    <li>JUKED</li>
    <li>JUKU(S)</li>
    <li>JULEP</li>
    <li>JUMBO</li>
    <li>JUMP(S)</li>
    <li>JUMPY</li>
    <li>JUN</li>
    <li>JUNCO</li>
    <li>JUNK(S)</li>
    <li>JUNKY</li>
    <li>JUNTA</li>
    <li>JUNTO</li>
    <li>JUPE(S)</li>
    <li>JUPON</li>
    <li>JURA</li>
    <li>JURAL</li>
    <li>JURAT</li>
    <li>JUREL</li>
    <li>JUROR</li>
    <li>JURY</li>
    <li>JUS</li>
    <li>JUST(S)</li>
    <li>JUT(S)</li>
    <li>JUTE(S)</li>
    <li>JUTTY</li>
    <li>KANJI</li>
    <li>KOJI</li>
    <li>KOPJE</li>
    <li>MAJOR</li>
    <li>MOJO(S)</li>
    <li>MUJIK</li>
    <li>NINJA</li>
    <li>OBJET</li>
    <li>PUJA(S)</li>
    <li>PUJAH</li>
    <li>PUNJI</li>
    <li>RAJ</li>
    <li>RAJA(S)</li>
    <li>RAJAH</li>
    <li>RAJES</li>
    <li>RIOJA</li>
    <li>SAJOU</li>
    <li>SHOJI</li>
    <li>SLOJD</li>
    <li>SOJA(S)</li>
    <li>TAJ</li>
    <li>TAJES</li>
    <li>THUJA</li>
  </ul>
</template>

<script>
export default {
  data () {
    return {}
  }
}
</script>

<style lang="scss" scoped>
</style>
